name: Build pipeline

on:
  workflow_dispatch:
  push:
  
jobs:
  build_and_test:
    name: Build / Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v1
